### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by brkn** [rails/website#16]
Can you please add licenses for the source code, and the blog posts in this repository.

**Comment by rafaelfranca** [comment]
@dhh should we make this repo some flavor of creative commons?

**Comment by rafaelfranca** [comment]
After discussing with DHH I learned that this repository is actually All Rights Reserved. https://choosealicense.com/no-permission/. Thanks for the issue.

**Comment by northeastprince** [comment]
[Isn't a CLA needed then?](https://choosealicense.com/no-permission/#:~:text=if%20you%E2%80%99re%20going%20to%20accept%20others%E2%80%99%20contributions%20to%20your%20non-licensed%20project%2C%20you%20may%20wish%20to%20explore%20adding%20a%20contributor%20agreement%20to%20your%20project%20with%20your%20lawyer%20so%20that%20you%20maintain%20copyright%20permission%20from%20contributors%2C%20even%20though%20you%E2%80%99re%20not%20granting%20the%20same.)
