### ISSUE TITLE
Suggestion to link to sponsors images

### ISSUE THREAD

**Issue by siaw23** [rails/website#167]
When you visit https://rubyonrails.org/world and scroll down, you'll see a list of sponsors. I think it'd be a nice touch to link the images somehow to the sponsors' sites. This will serve a few purposes:

1. An easy way to visit the sponsor's site
2. A way to find out what the sponsor does, for example. I don't know "The Agency" and can't find them on Google as there are quite a few "agencies".

@AmandaPerino 

<img width="1301" alt="Screenshot 2023-08-05 at 13 16 27" src="https://github.com/rails/website/assets/100293177/75e013e2-ed64-4735-9fe9-d5af00725e5f">

**Comment by AmandaPerino** [comment]
Done with #171

**Comment by AmandaPerino** [comment]
Thank you @siaw23 !
