### ISSUE TITLE
Homepage Example Improvements

### ISSUE THREAD

**Issue by craig-seeman** [rails/website#19]
Hi! I'm quite a bit unfamiliar with the rails framework and was looking upon the homepage examples and have a few suggestions to maybe lessen some confusion (that at least I was encountering). Or moreover, it may be just that these examples are intended for those with Software Engineering backgrounds to see these and 'fill in the blanks' instead of a concrete example of how to accomplish the example outlined.

`app/models/article.rb`
```ruby
  has_one_attached :avatar
```
One suggestion would be renaming this to `:picture` as I am believe it's meant to be a photo that is for the article, and not the avatar of the author.

`app/views/articles/show.html.erb`
```ruby
<%= image_tag @article.creator.avatar.url %>
```
This is where my knowledge of the 'magic' of the framework becomes a bit limited, however should this line read as `author` instead of `creator`, or is there some internal mapping that assumes the belongs_to and maps `creator` as such for us?

`app/views/articles/show.html.erb`
```ruby
<%= image_tag @article.creator.avatar.url %>
<%= @article.byline %>
```
Adding a sample of the byline method and showing its usage in the view might be helpful.

I would be more than happy to take this issue and create a PR with outlined fixes, I'm just wanting to make sure that my assumptions are correct and there is not framework 'magic' that is shown in these examples that I do not understand. 

Thanks!

**Comment by dhh** [comment]
Please do take a swing at these changes 👍. The code examples were just picked to give a flavor of usage, but we might as well make them as correct as possible.

**Comment by siaw23** [comment]
@craig-seeman, I grabbed this if you don't mind. https://github.com/rails/website/pull/43

Hopefully the intent of the code is clearer :)

**Comment by craig-seeman** [comment]
No worries @siaw23 :) I've been a very busy and unable to set time aside to do this. That pr looks great!
