### ISSUE TITLE
Features page headings use placeholder text

### ISSUE THREAD

**Issue by vlj91** [rails/website#223]
On the features page, each of the headings seem to use placeholder text, repeated throughout the page.

https://rubyonrails.org/features

<img width="1444" alt="image" src="https://github.com/rails/website/assets/10548294/23a0e9db-5634-4cc7-b59d-265c8fdd52da">

**Comment by zzak** [comment]
I think this page wasn't finished and isn't accessible from anywhere on the page, we could probably remove it?

**Comment by AmandaPerino** [comment]
@zzak Agree, can we unpublish this page (without deleting it)? In case we want to revisit this template in the future.
