### ISSUE TITLE
Update text describing ActionDispatch?

### ISSUE THREAD

**Issue by Aesthetikx** [rails/website#226]
https://github.com/rails/website/blame/4597a40aa915e9b22e63cbc55e59dd01df0d5574/index.html#L289

I am thinking 'ActionDispatch route URLs' sounds odd. I think it should be 'ActionDispatch routes URLs'?

- Active Records make modeling easy. ✅ 
- Action Controllers handle all requests. ✅ 
- Action Views mix Ruby and HTML. ✅ 
- Action Dispatch route URLs. ❓

**Comment by aniketpatidar** [comment]
@Aesthetikx  I would like to change this text.

**Comment by zzak** [comment]
Send a PR :bow:

**Comment by aniketpatidar** [comment]
Please review this [pull request](https://github.com/rails/website/pull/236) Thanks!

@zzak
