### ISSUE TITLE
Rails world website URL with a trailing slash giving 404

### ISSUE THREAD

**Issue by akhilgkrishnan** [rails/website#315]
### Current Behaviour 
1. https://rubyonrails.org/world/2024 - loading the page properly.
2. https://rubyonrails.org/world/2024/ -> Returning a 404 page.

### Expected Behaviour 
https://rubyonrails.org/world/2024/ should work properly as same https://rubyonrails.org/world/2024

cc: @AmandaPerino

**Comment by akhilgkrishnan** [comment]
I just noticed that this is not only happening in the world page, same issue is persist on some other website pages as well.
ref: https://rubyonrails.org/foundation/

**Comment by AmandaPerino** [comment]
@akhilgkrishnan Thanks for spotting this. Can you help fix it?
