### ISSUE TITLE
sidebar of edge site is misplaced

### ISSUE THREAD

**Issue by kmsheng** [rails/website#49]
<img width="1506" alt="Screen Shot 2022-06-28 at 12 13 31 PM" src="https://user-images.githubusercontent.com/880569/176090788-076f561c-c70b-4126-b954-8c381e47cb0f.png">

https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants_classic_mode.html#autoload-paths-and-eager-load-paths

mac m1 chrome 103.0
no errors from console

**Comment by kmsheng** [comment]
<img width="833" alt="Screen Shot 2022-06-28 at 12 16 00 PM" src="https://user-images.githubusercontent.com/880569/176091095-d4da8a5f-0641-41a5-9f07-96deb099689a.png">

demo code is "center" aligned ?

**Comment by fxn** [comment]
This guide does not belong to the edge guides (`classic` mode does not exist in Rails 7.0), so its rendering does not matter.

The HTML itself should not be there though, I'll see if we can do something to automate cleaning up orphan HTML files.

**Comment by fxn** [comment]
(By now, the HTML has been deleted.)
